# name: Update Submodule
# on:
#   push:
#     branches:
#       - main 

# jobs:
#   update-submodule:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code repository
#         uses: actions/checkout@v3
#         with:
#           repository: 'creatoroid/test'
#           token: ${{ secrets.GITHUB_TOKEN }}
#           path: 'test'

#       - name: Update submodule reference to latest commit from docs
#         run: |
#           cd test
#           git submodule update --init --recursive
#           git submodule set-branch --branch main doctest
#           git submodule update --remote
#           git config user.email 'github-actions[bot]@users.noreply.github.com'
#           git config user.name 'github-actions[bot]'
#           git add docs 
#           git commit -m "Update doctest submodule to latest commit"
#           git push
#         env:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}


name: Update Submodule

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git Config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Clone Code Repository and Update Submodule
        run: |
          git clone https://github.com/creatoroid/test.git
          cd test
          git submodule update --remote --merge
          git checkout -b new-branch-for-pr
          git add .
          git commit -m "Update docs submodule to latest commit"
          git push origin new-branch-for-pr

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "new-branch-for-pr"
          destination_branch: "main"
          pr_title: "Update Docs Submodule"
          pr_body: "This PR updates the Docs submodule to the latest commit."

