name: Update Submodule

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
        with:
          repository: 'creatoroid/test'
          ref: 'main'
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Create new branch for submodule update
        run: |
          git checkout -b sync-docs-submodule
          git submodule update --init --recursive
          git submodule foreach git pull origin main

      - name: Commit submodule reference
        run: |
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]'
          git commit -am "Update submodule reference"
          
      # The new action to create a fork, push to the fork and then create a pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          push-to-fork: 'github-actions[bot]'
          branch: 'sync-docs-submodule'
          delete-branch: true
          title: "Update submodule reference"
          body: "This PR updates the submodule references to the latest commit on the main branch."
          labels: "automated-pr"