name: Update Submodule

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Main Checkout code repository
        uses: actions/checkout@v2
        with:
          repository: 'creatoroid/test'
          ref: 'main'
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Create new branch for submodule update
        run: |
          git checkout -b sync-docs-submodule

      - name: Update submodule reference
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main
          
          # Configure git user and email for commit purposes
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]'
          
          # Commit the submodule changes
          git commit -am "Update submodule reference"

      # Push the changes to the new branch
      - name: Push changes to new branch
        run: git push origin sync-docs-submodule
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create Pull Request
      - name: Open a pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "sync-docs-submodule"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Update submodule reference"
          pr_body: "This PR updates the submodule references to the latest commit on the main branch."
          pr_label: "automated-pr"
