on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Main Checkout code repository
        uses: actions/checkout@v2
        with:
          repository: 'creatoroid/test'
          ref: 'main'
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Main Update submodule reference
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main
          
          # Configure git user and email for commit purposes
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]'
          
          # Commit the submodule changes
          git commit -am "Update submodule reference"
          
          # Push the changes back to the original repository
          git push origin main
        env:
          # Use the GITHUB_TOKEN provided by Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}